#!/usr/bin/env bash
# Merge deploy/compose.env (non-secrets) with OpenBao KV secret/v-note-stack/env
# and write deploy/.env for local docker compose.
#
# Usage:
#   export BAO_ADDR=https://secrets.desync.link   # or http://openbao-openbao-1:8200 on mini
#   export BAO_TOKEN=<token with read on secret/v-note-stack/env>
#   ./scripts/fetch-compose-env.sh
#
# Requires: curl, python3, deploy/compose.env

set -euo pipefail

ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
COMPOSE_ENV="${ROOT_DIR}/deploy/compose.env"
OUT_ENV="${ROOT_DIR}/deploy/.env"
KV_PATH="secret/v-note-stack/env"

: "${BAO_ADDR:?BAO_ADDR is required (e.g. https://secrets.desync.link)}"
: "${BAO_TOKEN:?BAO_TOKEN is required}"

for cmd in curl python3; do
  command -v "$cmd" >/dev/null || { echo "ERROR: $cmd not found"; exit 1; }
done

if [[ ! -f "$COMPOSE_ENV" ]]; then
  echo "ERROR: missing $COMPOSE_ENV"
  exit 1
fi

RESP=$(curl -sf -H "X-Vault-Token: ${BAO_TOKEN}" \
  "${BAO_ADDR%/}/v1/secret/data/${KV_PATH#secret/}" 2>/dev/null) || {
  echo "ERROR: failed to read OpenBao path secret/data/${KV_PATH#secret/} at ${BAO_ADDR}"
  exit 1
}

SECRET_KEYS=(POSTGRES_PASSWORD OIDC_CLIENT_SECRET)
python3 - "$COMPOSE_ENV" "$OUT_ENV" "$RESP" "${SECRET_KEYS[@]}" <<'PY'
import json, pathlib, shlex, sys

compose_path, out_path, resp_json, *required = sys.argv[1], sys.argv[2], sys.argv[3], *sys.argv[4:]
payload = json.loads(resp_json)
secrets = payload.get("data", {}).get("data", {})
missing = [k for k in required if not secrets.get(k)]
if missing:
    raise SystemExit(
        "ERROR: OpenBao secret/v-note-stack/env missing keys: " + ", ".join(missing)
    )

lines = []
lines.append("# Generated by scripts/fetch-compose-env.sh — do not commit.")
lines.append("")
lines.extend(pathlib.Path(compose_path).read_text().splitlines())
lines.append("")
lines.append("# --- OpenBao secrets (secret/v-note-stack/env) ---")
for key in sorted(secrets):
    lines.append(f"{key}={secrets[key]}")

pathlib.Path(out_path).write_text("\n".join(lines) + "\n")
PY

echo "Wrote ${OUT_ENV} ($(wc -l < "$OUT_ENV") lines, secrets from ${KV_PATH})"
