#!/bin/sh
# Write the gitignored deploy/.env for local docker compose: the committed
# non-secret defaults in deploy/compose.env plus a POSTGRES_PASSWORD.
#
# Usage:
#   ./scripts/local-compose-env.sh      # `just run-compose` calls this for you
#
# The password needs no secret store (#400). The local Postgres is a disposable
# container on one developer box, so nothing else ever has to know its password:
# it is generated here the first time and then kept.
#
# Kept, not regenerated: Postgres fixes the password when it initialises the
# volume, so a fresh value on every run would lock the stack out of its own
# database. An existing deploy/.env's POSTGRES_PASSWORD is therefore carried
# over verbatim — which is also what keeps a deploy/.env written by the old
# store-backed script working against the volume it already initialised. To
# start over, remove both deploy/.env and the volume (DB_VOLUME in compose.env).
#
# Everything else is rebuilt from deploy/compose.env on every run, so edits
# there take effect, and keys that are no longer in it are dropped.
#
# POSIX sh with no python: scripts/test-local-compose-env.sh runs it in the
# docker:27-cli CI image, which has neither bash nor python.

set -eu

ROOT_DIR=$(cd "$(dirname "$0")/.." && pwd)
COMPOSE_ENV="${ROOT_DIR}/deploy/compose.env"
OUT_ENV="${ROOT_DIR}/deploy/.env"

if [ ! -f "$COMPOSE_ENV" ]; then
  echo "ERROR: missing $COMPOSE_ENV" >&2
  exit 1
fi

# Last assignment wins, matching how compose reads a duplicated key. Everything
# after the first `=` is the value — an old stored password may contain `=`.
PASSWORD=""
if [ -f "$OUT_ENV" ]; then
  PASSWORD=$(sed -n 's/^POSTGRES_PASSWORD=//p' "$OUT_ENV" | tail -n 1)
fi

if [ -n "$PASSWORD" ]; then
  SOURCE="kept from existing deploy/.env"
else
  # Kept per checkout, but the volume name is machine-wide: a second clone or
  # worktree, or a deploy/.env deleted on its own, would otherwise generate a
  # password the existing volume rejects with a bare auth failure. When docker
  # is absent or unreachable there is nothing to check, and generation goes on.
  DB_VOLUME=$(sed -n 's/^DB_VOLUME=//p' "$COMPOSE_ENV" | tail -n 1)
  DB_VOLUME=${DB_VOLUME:-v-note-local-db}
  if command -v docker >/dev/null 2>&1 \
    && docker volume inspect "$DB_VOLUME" >/dev/null 2>&1; then
    echo "ERROR: volume $DB_VOLUME exists but deploy/.env has no POSTGRES_PASSWORD." >&2
    echo "Copy deploy/.env from the checkout that created the volume, or remove the" >&2
    echo "volume to start the local database over: docker volume rm $DB_VOLUME" >&2
    exit 1
  fi
  # Hex, so the value needs no quoting in an env file or a connection string.
  PASSWORD=$(od -An -N24 -tx1 /dev/urandom | tr -d ' \n')
  if [ ${#PASSWORD} -ne 48 ]; then
    echo "ERROR: failed to generate a password from /dev/urandom" >&2
    exit 1
  fi
  SOURCE="generated"
fi

# Written beside the target and renamed over it, so an interrupted run never
# leaves a half-written file — the password in it is the only copy there is.
umask 077
TMP=$(mktemp "${OUT_ENV}.XXXXXX")
trap 'rm -f "$TMP"' EXIT
{
  echo "# Generated by scripts/local-compose-env.sh — do not commit."
  echo
  cat "$COMPOSE_ENV"
  echo
  echo "# --- Local-only secret: generated once, then kept (see the script) ---"
  echo "POSTGRES_PASSWORD=${PASSWORD}"
} > "$TMP"
mv "$TMP" "$OUT_ENV"
trap - EXIT

echo "Wrote ${OUT_ENV} (POSTGRES_PASSWORD ${SOURCE})"
