#!/bin/sh
# Exercise scripts/local-compose-env.sh in a scratch tree, never the real deploy/.
#
# The one property that matters is that the password is generated ONCE: Postgres
# fixes it when it initialises the volume, so a script that regenerates on a
# later run leaves the local stack unable to open its own database, and nothing
# says why. Every other case here is secondary to "a second run keeps it".
#
# POSIX sh, not bash: this runs in the `docker:27-cli` CI image (no bash, no
# python) alongside test-deploy-v-note.sh.
set -eu

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

FAILURES=0
fail() {
  echo "FAIL: $*"
  FAILURES=$((FAILURES + 1))
}
pass() {
  echo "ok: $*"
}

# A fresh tree per case: its own copy of the script (which locates deploy/ from
# its own path) and of the committed compose.env.
new_tree() {
  tree="$WORK/$1"
  mkdir -p "$tree/scripts" "$tree/deploy"
  cp "$ROOT/scripts/local-compose-env.sh" "$tree/scripts/"
  cp "$ROOT/deploy/compose.env" "$tree/deploy/"
  echo "$tree"
}

password_in() {
  sed -n 's/^POSTGRES_PASSWORD=//p' "$1" | tail -n 1
}

# --- generates a password when deploy/.env is absent ----------------------------
T=$(new_tree fresh)
if "$T/scripts/local-compose-env.sh" >/dev/null; then
  P1=$(password_in "$T/deploy/.env")
  if printf '%s' "$P1" | grep -Eq '^[0-9a-f]{48}$'; then
    pass "generates a 48-hex-char password when deploy/.env is absent"
  else
    fail "generated password is not 48 hex chars: '$P1'"
  fi
  # The file holds the only copy of a credential; it should not be world-readable.
  MODE=$(stat -c '%a' "$T/deploy/.env")
  if [ "$MODE" = "600" ]; then
    pass "deploy/.env is written mode 600"
  else
    fail "deploy/.env mode is $MODE, want 600"
  fi
else
  fail "script failed on a fresh tree"
  P1=""
fi

# --- does not regenerate when one exists ---------------------------------------
"$T/scripts/local-compose-env.sh" >/dev/null
P2=$(password_in "$T/deploy/.env")
if [ -n "$P1" ] && [ "$P1" = "$P2" ]; then
  pass "a second run keeps the password"
else
  fail "a second run changed the password ('$P1' -> '$P2')"
fi
if [ "$(grep -c '^POSTGRES_PASSWORD=' "$T/deploy/.env")" = "1" ]; then
  pass "a second run does not duplicate POSTGRES_PASSWORD"
else
  fail "POSTGRES_PASSWORD appears more than once after a second run"
fi

# --- two fresh trees get different passwords -----------------------------------
T2=$(new_tree fresh2)
"$T2/scripts/local-compose-env.sh" >/dev/null
if [ "$(password_in "$T2/deploy/.env")" != "$P1" ]; then
  pass "separate trees get separately generated passwords"
else
  fail "two fresh trees generated the same password"
fi

# --- merges compose.env, and picks up edits to it ------------------------------
MISSING=""
while IFS= read -r line; do
  case "$line" in
    '' | '#'*) continue ;;
  esac
  grep -qxF "$line" "$T/deploy/.env" || MISSING="$MISSING $line"
done < "$ROOT/deploy/compose.env"
if [ -z "$MISSING" ]; then
  pass "every compose.env assignment is carried into deploy/.env"
else
  fail "compose.env lines missing from deploy/.env:$MISSING"
fi

echo "ADDED_BY_TEST=1" >> "$T/deploy/compose.env"
"$T/scripts/local-compose-env.sh" >/dev/null
if grep -qx 'ADDED_BY_TEST=1' "$T/deploy/.env" && [ "$(password_in "$T/deploy/.env")" = "$P1" ]; then
  pass "a compose.env edit propagates and the password survives it"
else
  fail "a compose.env edit did not propagate, or it changed the password"
fi

# --- a deploy/.env from the retired store-backed script keeps working -----------
# That script wrote every stored key raw, sorted, after compose.env — so a
# password can contain `=`, `+` and `/`, and a retired key rode along with it.
T=$(new_tree legacy)
LEGACY_PW='aB3+/xY=z=='
{
  echo "# Generated by the old script — do not commit."
  cat "$ROOT/deploy/compose.env"
  echo
  echo "OIDC_CLIENT_SECRET=retired-value"
  echo "POSTGRES_PASSWORD=$LEGACY_PW"
} > "$T/deploy/.env"
"$T/scripts/local-compose-env.sh" >/dev/null
if [ "$(password_in "$T/deploy/.env")" = "$LEGACY_PW" ]; then
  pass "an existing password is kept verbatim, including = + /"
else
  fail "legacy password not kept verbatim: '$(password_in "$T/deploy/.env")'"
fi
if grep -q '^OIDC_CLIENT_SECRET=' "$T/deploy/.env"; then
  fail "a key no longer in compose.env was carried over"
else
  pass "keys that are not in compose.env are dropped"
fi

# --- an empty password is treated as absent ------------------------------------
T=$(new_tree empty)
echo "POSTGRES_PASSWORD=" > "$T/deploy/.env"
"$T/scripts/local-compose-env.sh" >/dev/null
if printf '%s' "$(password_in "$T/deploy/.env")" | grep -Eq '^[0-9a-f]{48}$'; then
  pass "an empty POSTGRES_PASSWORD is replaced with a generated one"
else
  fail "an empty POSTGRES_PASSWORD was not replaced"
fi

# --- missing compose.env fails without touching deploy/.env --------------------
T=$(new_tree nocompose)
rm "$T/deploy/compose.env"
echo "POSTGRES_PASSWORD=keep-me" > "$T/deploy/.env"
if "$T/scripts/local-compose-env.sh" >/dev/null 2>&1; then
  fail "script succeeded with no compose.env"
elif [ "$(cat "$T/deploy/.env")" = "POSTGRES_PASSWORD=keep-me" ]; then
  pass "a missing compose.env fails and leaves deploy/.env untouched"
else
  fail "a missing compose.env failed but rewrote deploy/.env"
fi

# --- no temp files left behind -------------------------------------------------
if ls "$WORK"/*/deploy/.env.* >/dev/null 2>&1; then
  fail "temp files left in deploy/: $(ls "$WORK"/*/deploy/.env.*)"
else
  pass "no temp files left behind"
fi

if [ "$FAILURES" -ne 0 ]; then
  echo "$FAILURES failure(s)"
  exit 1
fi
echo "all local-compose-env cases passed"
